# Site settings
title: "'t Ringwinkeltje"
description: >- # this means to ignore newlines until "baseurl:"
  A responsive site template designed by HTML5 Up,<br>
  ported to Jekyll by MOODULE<br>
  and released under the Creative Commons.

# Contact information
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555
email: youremailaddress@gmail.com

# Social settings
500px_url: https://www.google.com
facebook_url: https://www.google.com
github_url: https://www.google.com
gitlab_url: https://www.google.com
instagram_url: https://www.google.com
linkedin_url: https://www.google.com
pinterest_url: https://www.google.com
slack_url: https://www.google.com
twitter_url: https://www.google.com

# Optional elements
logo: /assets/images/logo.png
favicon: /assets/images/favicon.ico
legal_terms:
  url: /en/legal-terms/
privacy_policy:
  url: /en/privacy-policy/
  third_party:
    hosting: github

# Recaptcha in forms
recaptcha:
  sitekey: 6LdzdcgUAAAAAF-3fFepKyWHRf0Yg1PHegY8z-pl

# Collections
collections:
  :
    output: false
    date: 2019-05-07
  shiva:
    output: false
    date: 2019-05-08

# Default settings
defaults:
  -
    scope:
      type: "redirects"
    values:
      layout: "redirect"
      lang: "x-default"
  -
    scope:
      path: ""
    values:
      menu: default
  -
    scope:
      path: "nl"
    values:
      lang: "nl"
  # -
  #   scope:
  #     path: "fr"
  #   values:
  #     lang: "fr"

# Build settings
permalink: pretty
markdown: kramdown
sass:
  style: compressed

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dekreno.github.io/tringwinkeltje" # the base hostname & protocol for your site, e.g. http://example.com
author: Myriam en Annie
copyright_holder: tringwinkeltje

# Exclude from processing
