# Site settings
title: "'t Ringwinkeltje"
description: 'Ringen door Myriam en Annie'
baseurl: "/tringwinkeltje/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author:

# Collection settings
collections:
  photos:

# Social settings
facebook_url:
instagram_url:
pinterest_url:

# Build settings
markdown: kramdown
